version: '3'

services:
  wordpress:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./wordpress_data:/var/www/html/wp-content
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example

  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress

volumes:
  wordpress_data:
  db_data:
